FROM java:8-jre
MAINTAINER Mallcloud zscat <951449465@qq.com>

ADD ./jar/cloud-monitor-*.jar /app/app.jar

EXPOSE 10002

ENV JAVA_OPTS="-Xmx256m -Xms256m"
ENV CONFIG_PROFILE="test"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 -Duser.timezone=GMT+08 \
-Djava.security.egd=file:/dev/./urandom \
-Dspring.profiles.active=$CONFIG_PROFILE \
-jar /app/app.jar"]
