FROM java:8-jre
MAINTAINER Mallcloud zscat <951449465@qq.com>

ADD ./jar/cloud-registry-*.jar /app/app.jar

EXPOSE 9000

ENV JAVA_OPTS="-Xmx256m -Xms256m"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 \
-Duser.timezone=GMT+08 \
-Djava.security.egd=file:/dev/./urandom \
-jar /app/app.jar"]

