FROM java:8-jre
MAINTAINER Mallcloud zscat <951449465@qq.com>

ADD ./jar/mallcloud-gateway-*.jar /app/app.jar

EXPOSE 10000

ENV JAVA_OPTS="-Xmx256m -Xms256m"
ENV CONFIG_PROFILE=test

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 -Duser.timezone=GMT+08 \
-Djava.security.egd=file:/dev/./urandom \
-jar /app/app.jar \
--spring.profiles.active=$CONFIG_PROFILE"]
